# torchtitan Config.toml

[job]
dump_folder = "./outputs"
description = "test"
print_args = true
use_for_integration_test = true

[profiling]
enable_profiling = false
save_traces_folder = "profile_trace"
profile_freq = 10
enable_memory_snapshot = false
save_memory_snapshot_folder = "memory_snapshot"

[metrics]
log_freq = 1
log_norm_freq = 1
disable_color_printing = false
enable_tensorboard = false
save_tb_folder = "tb"
enable_wandb = true
wandb_project = "test-project"
wandb_group = "test-group"
wandb_name = "test-run"

[model]
name = "bit_byte_llama3"
flavor = "debugmodel"
norm_type = "rmsnorm" # layernorm / np_layernorm / rmsnorm / np_rmsnorm
first_in_init_fn_type = "normal"
first_in_exp = -0.5
intermediate_init_fn_type = "normal"
intermediate_init_std = 1.0
intermediate_exp = -0.5
init_gate_as_residual = False
final_out_init_fn_type = "normal"
final_out_exp = -1.0
# tokenizer_path = ???
# converters = ???

[optimizer]
name = "Scion"
lr = 3e-4
eps = 1e-12
weight_decay = 0
is_light = true
is_unconstrained = true
backend_steps = 5
momentum = 0.1
nesterov = false
embed_lr = 3e-4
unembed_lr = 3e-4
embed_str_match = "tok_embeddings.weight"
unembed_str_match = "output.weight"
implementation = "fused" # for AdamW

[lr_scheduler]
warmup_steps = 200  # lr scheduler warm up, normally 20% of the train steps
decay_ratio = 0.25
decay_type = "linear"  # linear / cosine / sqrt
lr_min = 0.0

[training]
seed = 1
dataset_path = "./data"
steps = 10
seq_len = 4096
local_batch_size = 4
global_batch_size = 4
max_norm = 1  # grad norm clipping

[parallelism]
data_parallel_replicate_degree = 1
data_parallel_shard_degree = -1
fsdp_reshard_after_forward = "default" # default / never / always
tensor_parallel_degree = 1
mixed_precision_param = "bfloat16"
mixed_precision_reduce = "float32"
context_parallel_degree = 1
pipeline_parallel_degree = 1
enable_async_tensor_parallel = false

[checkpoint]
enable_checkpoint = false
folder = "checkpoint"
interval_type = "steps"
interval = 10
model_weights_only = false
export_dtype = "bfloat16"
async_mode = "disabled"  # ["disabled", "async", "async_with_pinned_mem"]

[compile]
enable = false
components = ["model", "loss"]

[activation_checkpoint]
mode = 'none'  # ['none', 'selective', 'full']
selective_ac_option = '2'  # 'int' = ac every positive int layer or 'op', ac based on ops policy

[float8]
enable_fsdp_float8_all_gather = false
precompute_float8_dynamic_scale_for_fsdp = false
